name: Bug Report
description: Report a bug in the Soberano theme
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the fields below.

  - type: input
    id: hugo-version
    attributes:
      label: Hugo version
      description: "Output of `hugo version`"
      placeholder: "hugo v0.156.0+extended darwin/arm64"
    validations:
      required: true

  - type: dropdown
    id: privacy-mode
    attributes:
      label: Privacy mode
      options:
        - standard (default)
        - hardened
        - paranoid
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug.
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Relevant config
      description: Paste relevant sections of your `hugo.toml` (remove sensitive data).
      render: toml

  - type: textarea
    id: logs
    attributes:
      label: Build output / error logs
      description: Paste any relevant Hugo build output.
      render: text
